#!/usr/bin/env python3
"""Generate current Conformance and Human/Agent history crosswalk views."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import sys

import yaml

ROOT = Path(__file__).resolve().parents[1]
AGENT_CONFORMANCE_URL = "https://github.com/LucasLu3918/ai-product-system/blob/main/orchestration/CONFORMANCE.md"
sys.path.insert(0, str(ROOT / "scripts"))
from scenario_conformance import analyze  # noqa: E402


def build_current_summary(registry: Path | None = None, scenarios: Path | None = None) -> str:
    result = analyze(registry or ROOT / "tests/scenario_coverage.yaml", scenarios or ROOT / "tests/scenarios")
    if result.get("status") != "PASS":
        raise ValueError("canonical Scenario Conformance check failed: " + "; ".join(result.get("errors") or []))
    coverage = result["coverage"]
    total = int(coverage["total"])
    automated_types = ("deterministic", "lifecycle", "agent_eval")
    automated = sum(int(coverage.get(kind) or 0) for kind in automated_types)
    manual_ids: list[str] = []
    uncovered_ids: list[str] = []
    data = yaml.safe_load((registry or ROOT / "tests/scenario_coverage.yaml").read_text(encoding="utf-8")) or {}
    for row in data.get("scenarios") or []:
        kind = str(row.get("coverage") or "")
        if kind in {"manual", "uncovered"}:
            (manual_ids if kind == "manual" else uncovered_ids).append(str(row.get("id") or "").zfill(3))
    lines = [
        "<!-- Generated by scripts/conformance_summary.py; edit tests/scenario_coverage.yaml instead. -->",
        "# Current Scenario Conformance",
        "",
        "This is a deterministic view of `tests/scenario_coverage.yaml` and the Scenario inventory. It is not a quality score.",
        "",
        f"- Registry status: **{result['status']}**",
        f"- Scenarios: **{total}** (registered {coverage['registered']}; missing {coverage['missing']})",
        f"- Automated evidence: **{automated}/{total} ({coverage['automated_percent']:.1f}%)**",
        "- Automated denominator: `deterministic + lifecycle + agent_eval`; specifications alone do not count.",
        f"- Deterministic: {coverage['deterministic']}",
        f"- Lifecycle: {coverage['lifecycle']}",
        f"- Agent Eval: {coverage['agent_eval']}",
        f"- Manual: {coverage['manual']} ({', '.join(manual_ids) if manual_ids else 'none'})",
        f"- Uncovered: {coverage['uncovered']} ({', '.join(uncovered_ids) if uncovered_ids else 'none'})",
        "",
        "`manual` remains visible and is not represented as automated coverage. Any missing entry, stale evidence or `uncovered` classification remains governed by the canonical checker and release policy.",
        "",
        f"For normative Agent admission and validation rules, see [orchestration/CONFORMANCE.md]({AGENT_CONFORMANCE_URL}).",
        "For preserved versioned Human history, see [CONFORMANCE_HISTORY_INDEX.md](CONFORMANCE_HISTORY_INDEX.md).",
        "",
    ]
    return "\n".join(lines)


def _slug(text: str) -> str:
    value = text.strip().lower()
    value = re.sub(r"[`*_]", "", value)
    value = re.sub(r"[^\w\- ]", "", value, flags=re.UNICODE)
    return re.sub(r"\s+", "-", value).strip("-")


def _headings(path: Path) -> list[tuple[int, str, str]]:
    rows = []
    counts: dict[str, int] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^(#{1,6})\s+(.+?)\s*#*\s*$", line)
        if not match:
            continue
        title = match.group(2).strip()
        slug = _slug(title)
        duplicate = counts.get(slug, 0)
        counts[slug] = duplicate + 1
        anchor = f"{slug}-{duplicate}" if duplicate else slug
        rows.append((len(match.group(1)), title, anchor))
    return rows


def build_history_index(human_path: Path | None = None, agent_path: Path | None = None) -> str:
    human_path = human_path or ROOT / "docs/human/CONFORMANCE.md"
    agent_path = agent_path or ROOT / "orchestration/CONFORMANCE.md"
    lines = [
        "<!-- Generated by scripts/conformance_summary.py; source documents remain authoritative. -->",
        "# Conformance History and Normative Crosswalk",
        "",
        "Each retained section maps to its existing anchor. Human versioned baselines remain history; Agent-facing rules remain normative in the orchestration document.",
        "",
        "| Source section | Destination role |",
        "|---|---|",
    ]
    for path, label in ((human_path, "Human Conformance"), (agent_path, "Agent Conformance")):
        relative = (AGENT_CONFORMANCE_URL if path.resolve() == (ROOT / "orchestration/CONFORMANCE.md").resolve()
                    else os.path.relpath(path, ROOT / "docs/human").replace(os.sep, "/"))
        for level, title, anchor in _headings(path):
            history = label.startswith("Human") and (title.lower().startswith("v0.") or "baseline" in title.lower() or "legacy" in title.lower())
            destination = "Historical record" if history else "Normative rule" if label.startswith("Agent") else "Current Human guidance"
            lines.append(f"| [{'#' * level} {title}]({relative}#{anchor}) | {destination} |")
    lines += ["", "The crosswalk preserves source anchors. Edit the source documents for content changes, then regenerate this index.", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("view", choices=("current", "history"))
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", type=Path)
    args = parser.parse_args()
    try:
        rendered = build_current_summary() if args.view == "current" else build_history_index()
        if args.check:
            current = args.check.read_text(encoding="utf-8")
            if current != rendered:
                print(f"STALE: regenerate {args.check}")
                return 1
        if args.output:
            args.output.write_text(rendered, encoding="utf-8")
        else:
            print(rendered, end="")
    except (OSError, UnicodeError, yaml.YAMLError, ValueError) as exc:
        print(f"CONFORMANCE SUMMARY BLOCKED: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
