"""Generate the compatible v1 Skill registry from canonical Skill frontmatter."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
HEADER = "# Generated by scripts/skill_index.py; edit SKILL.md frontmatter instead.\n"


class UniqueLoader(yaml.SafeLoader):
    """Reject ambiguous duplicate metadata keys."""


def unique_mapping(loader, node):
    result = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node)
        if key in result:
            raise ValueError(f"duplicate metadata key: {key}")
        result[key] = loader.construct_object(value_node)
    return result


UniqueLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping
)


def generate(root: Path) -> dict:
    base = root.resolve()
    skills_root = base / "skills"
    if skills_root.is_symlink():
        raise ValueError("skills directory cannot be a symlink")
    entries = {}
    for path in sorted(skills_root.rglob("SKILL.md")):
        if path.is_symlink() or not path.resolve().is_relative_to(
            skills_root.resolve()
        ):
            raise ValueError("Skill source must remain inside skills/")
        match = re.match(
            r"\A---\r?\n(.*?)\r?\n---(?:\r?\n|$)",
            path.read_text(encoding="utf-8"),
            re.DOTALL,
        )
        if not match:
            raise ValueError(f"missing frontmatter: {path.relative_to(base)}")
        meta = yaml.load(match.group(1), Loader=UniqueLoader)
        if not isinstance(meta, dict):
            raise TypeError("Skill metadata must be a mapping")
        sid = meta.get("id")
        if not isinstance(sid, str) or not re.fullmatch(
            r"[a-z0-9]+(?:-[a-z0-9]+)*", sid
        ):
            raise ValueError("invalid Skill id")
        if sid in entries:
            raise ValueError(f"duplicate Skill id: {sid}")
        if "applies_when" in meta:
            raise ValueError(f"{sid}: migrate applies_when into canonical triggers")
        description = meta.get("description")
        if not isinstance(description, str) or not 1 <= len(description.strip()) <= 1024:
            raise ValueError(f"{sid}: description must contain 1-1024 characters")
        capability = meta.get("capability")
        cost = meta.get("estimated_context_cost")
        triggers = meta.get("triggers")
        requirements = meta.get("model_requirements")
        if (
            not isinstance(capability, str)
            or not capability.strip()
            or cost not in {"low", "medium", "high"}
        ):
            raise ValueError(f"{sid}: capability and context cost required")
        if (
            not isinstance(triggers, list)
            or not triggers
            or any(not isinstance(t, str) or not t.strip() for t in triggers)
            or len(triggers) != len(set(triggers))
        ):
            raise ValueError(f"{sid}: unique nonempty triggers required")
        if not isinstance(requirements, dict):
            raise TypeError(f"{sid}: model requirements required")
        choices = {
            "reasoning": {"low", "medium", "high", "very_high"},
            "coding": {"none", "normal", "strong"},
            "reliability": {"normal", "high", "critical"},
        }
        if set(requirements) != {*choices, "minimum_tier", "preferred_tier"}:
            raise ValueError(f"{sid}: unsupported model requirement fields")
        for key, allowed in choices.items():
            if (
                not isinstance(requirements.get(key), str)
                or requirements[key] not in allowed
            ):
                raise ValueError(f"{sid}: invalid {key}")
        tiers = [requirements.get(key) for key in ("minimum_tier", "preferred_tier")]
        if (
            any(type(t) is not int or t not in range(1, 5) for t in tiers)
            or tiers[0] > tiers[1]
        ):
            raise ValueError(f"{sid}: invalid model tiers")
        entries[sid] = {
            "description": description,
            "capability": capability,
            "path": path.relative_to(skills_root).as_posix(),
            "triggers": triggers,
            "cost": cost,
            "model_requirements": requirements,
        }
    if not entries:
        raise ValueError("no Skill sources found")
    return {"version": 1, "skills": dict(sorted(entries.items()))}


def render(root: Path) -> str:
    return HEADER + yaml.safe_dump(generate(root), sort_keys=False, allow_unicode=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument(
        "--write",
        action="store_true",
        help="Regenerate INDEX.yaml; default checks drift without writes",
    )
    args = parser.parse_args()
    try:
        root = args.root.resolve()
        expected = render(root)
        target = root / "skills/INDEX.yaml"
        if target.is_symlink():
            raise ValueError("registry target cannot be a symlink")
        if args.write:
            target.write_text(expected, encoding="utf-8")
        elif not target.is_file() or target.read_text(encoding="utf-8") != expected:
            raise ValueError(
                "Skill registry drift; run python scripts/skill_index.py --write"
            )
    except (OSError, ValueError, TypeError, yaml.YAMLError) as exc:
        print(f"FAIL: {exc}")
        return 1
    print("Skill registry PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
